version: '3'
services:
  nicofyi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
        - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - TURSO_DB_URL=${TURSO_DB_URL}
        - TURSO_DB_AUTH_TOKEN=${TURSO_DB_AUTH_TOKEN}
        - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
        - POSTHOG_API_KEY=${POSTHOG_API_KEY}
        - POSTHOG_PROJECT_ID=${POSTHOG_PROJECT_ID}
        - POSTHOG_INSIGHT_ID=${POSTHOG_INSIGHT_ID}
        - POSTGRES_DB_URL=${POSTGRES_DB_URL}
        - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
        - GOOGLE_SHEETS_API_KEY=${GOOGLE_SHEETS_API_KEY}
        - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
        - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    networks:
      - coolify
    restart: unless-stopped
    environment:
      - NODE_ENV=production
networks:
  coolify:
    external: true
