// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    MAILCHIMP_API_SERVER: z.string().optional(),
    MAILCHIMP_AUDIENCE_ID: z.string().optional(),
    BUTTONDOWN_API_KEY: z.string().optional(),
    CONVERTKIT_API_KEY: z.string().optional(),
    CONVERTKIT_FORM_ID: z.string().optional(),
    KLAVIYO_API_KEY: z.string().optional(),
    KLAVIYO_LIST_ID: z.string().optional(),
    REVUE_API_KEY: z.string().optional(),
    EMAILOCTOPUS_API_KEY: z.string().optional(),
    EMAILOCTOPUS_LIST_ID: z.string().optional(),
    GITHUB_TOKEN: z.string().optional(),
    TURSO_DB_URL: z.string().min(1),
    TURSO_DB_AUTH_TOKEN: z.string().min(1),
    RECAPTCHA_SECRET_KEY: z.string().min(1),
    POSTHOG_API_KEY: z.string().min(1),
    POSTHOG_PROJECT_ID: z.string().min(1),
    POSTHOG_INSIGHT_ID: z.string().min(1),
    POSTGRES_DB_URL: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_GISCUS_REPO: z.string().optional(),
    NEXT_PUBLIC_GISCUS_REPOSITORY_ID: z.string().optional(),
    NEXT_PUBLIC_GISCUS_CATEGORY: z.string().optional(),
    NEXT_PUBLIC_GISCUS_CATEGORY_ID: z.string().optional(),
    NEXT_PUBLIC_UTTERANCES_REPO: z.string().optional(),
    NEXT_PUBLIC_DISQUS_SHORTNAME: z.string().optional(),
    NEXT_PUBLIC_SHOW_ALL_POSTS: z.string().optional(),
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: z.string().min(1),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_GISCUS_REPO: process.env.NEXT_PUBLIC_GISCUS_REPO,
    NEXT_PUBLIC_GISCUS_REPOSITORY_ID: process.env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID,
    NEXT_PUBLIC_GISCUS_CATEGORY: process.env.NEXT_PUBLIC_GISCUS_CATEGORY,
    NEXT_PUBLIC_GISCUS_CATEGORY_ID: process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID,
    NEXT_PUBLIC_UTTERANCES_REPO: process.env.NEXT_PUBLIC_UTTERANCES_REPO,
    NEXT_PUBLIC_DISQUS_SHORTNAME: process.env.NEXT_PUBLIC_DISQUS_SHORTNAME,
    NEXT_PUBLIC_SHOW_ALL_POSTS: process.env.NEXT_PUBLIC_SHOW_ALL_POSTS,
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  },
})
